# This file is used by Google Cloud Build.

steps:

# Build the Docker image.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-east1-docker.pkg.dev/peachy-tools-319613/peachy-tools:9.0'
    - '.'
  dir: 'src'

# Deploy the Docker image to Cloud Run.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'peachy-tools'
    - '--image'
    - 'us-east1-docker.pkg.dev/peachy-tools-319613/peachy-tools:9.0'
    - '--region'
    - 'us-east1'
    - '--platform'
    - 'managed'

images:
  - 'us-east1-docker.pkg.dev/peachy-tools-319613/peachy-tools:9.0'
