const WORDS = [

    // Animals
    "Aardvark",
    "Alligator",
    "Ant",
    "Antelope",
    "Ape",
    "Armadillo",
    "Baboon",
    "Badger",
    "Bat",
    "Bear",
    "Beaver",
    "Bee",
    "Bird",
    "Boar",
    "Buffalo",
    "Butterfly",
    "Bull",
    "Calf",
    "Camel",
    "Caribou",
    "Cat",
    "Caterpillar",
    "Cattle",
    "Chameleon",
    "Cheetah",
    "Chicken",
    "Chimpanzee",
    "Cobra",
    "Cockroach",
    "Cougar",
    "Coyote",
    "Crab",
    "Crane",
    "Crocodile",
    "Crow",
    "Deer",
    "Dinosaur",
    "Dog",
    "Dolphin",
    "Donkey",
    "Dove",
    "Dragonfly",
    "Duck",
    "Eagle",
    "Eel",
    "Elephant",
    "Elk",
    "Falcon",
    "Fish",
    "Flamingo",
    "Fly",
    "Fox",
    "Frog",
    "Gazelle",
    "Gecko",
    "Giraffe",
    "Goat",
    "Goose",
    "Gorilla",
    "Grasshopper",
    "Hamster",
    "Hare",
    "Hawk",
    "Hedgehog",
    "Hippopotamus",
    "Hornet",
    "Horse",
    "Human",
    "Hyena",
    "Jaguar",
    "Jay",
    "Jellyfish",
    "Kangaroo",
    "Koala",
    "Leopard",
    "Lion",
    "Lizard",
    "Llama",
    "Lobster",
    "Mammoth",
    "Mandrill",
    "Meerkat",
    "Mink",
    "Mole",
    "Mongoose",
    "Monkey",
    "Moose",
    "Mosquito",
    "Mouse",
    "Newt",
    "Octopus",
    "Orangutan",
    "Ostrich",
    "Otter",
    "Owl",
    "Oyster",
    "Panther",
    "Parrot",
    "Panda",
    "Pelican",
    "Penguin",
    "Pig",
    "Pigeon",
    "Pony",
    "Porcupine",
    "Pug",
    "Rabbit",
    "Raccoon",
    "Ram",
    "Rat",
    "Raven",
    "Reindeer",
    "Rhinoceros",
    "Salamander",
    "Salmon",
    "Sardine",
    "Seal",
    "Shark",
    "Sheep",
    "Skunk",
    "Sloth",
    "Snail",
    "Snake",
    "Spider",
    "Squid",
    "Squirrel",
    "Stegosaurus",
    "Swan",
    "Tiger",
    "Toad",
    "Turkey",
    "Turtle",
    "Viper",
    "Vulture",
    "Walrus",
    "Wasp",
    "Weasel",
    "Whale",
    "Wolf",
    "Wolverine",
    "Woodpecker",
    "Worm",
    "Yak",
    "Zebra",

    // Cities
    "New York",
    "Toronto",

    // Companies
    "Alphabet",
    "Amazon",
    "Google",
    "Honda",
    "Microsoft",
    "Tesla",
    "Toyota",
    "Walmart",

    // Fruits
    "Apple",
    "Apricots",
    "Avocado",
    "Banana",
    "Blackberry",
    "Blueberry",
    "Cantaloupe",
    "Cherries",
    "Clementine",
    "Cranberries",
    "Dragonfruit",
    "Durian",
    "Figs",
    "Grapefruit",
    "Grapes",
    "Guava",
    "Jackfruit",
    "Kiwifruit",
    "Lemon",
    "Lime",
    "Mandarin",
    "Mango",
    "Nectarine",
    "Olives",
    "Orange",
    "Papaya",
    "Peaches",
    "Pear",
    "Pineapple",
    "Plantain",
    "Plum",
    "Pomegranate",
    "Prune",
    "Raspberry",
    "Rhubarb",
    "Sapodilla",
    "Strawberry",
    "Tangerine",
    "Watermelon",

    // Continents
    "Africa",
    "Antarctica",
    "Asia",
    "Australia",
    "Europe",

    // Countries
    "Canada",

    // Sports
    "Basketball",
    "Baseball",
    "Cricket",
    "Football",
    "Hockey",
    "Soccer",

    // Stationery
    "Binder",
    "Case",
    "Eraser",
    "Paper",
    "Pen",
    "Pencil",
    "Ruler",

    // Vegetables
    "Asparagus",
    "Beans",
    "Beets",
    "Broccoli",
    "Cabbage",
    "Carrot",
    "Cauliflower",
    "Celery",
    "Corn",
    "Cucumber",
    "Eggplant",
    "Fennel",
    "Horseradish",
    "Kale",
    "Leeks",
    "Lettuce",
    "Mushrooms",
    "Onions",
    "Peas",
    "Pepper",
    "Potato",
    "Pumpkin",
    "Radishes",
    "Spinach",
    "Squash",
    "Tomato",
    "Turnip",
    "Yam",
    "Zucchini",
];

function getRandomWords(numOfWords) {
    if (WORDS.length < numOfWords) {
        return null;
    }

    let selectedWords = [];
    while (selectedWords.length < numOfWords) {
        let randIndex = Math.floor(Math.random() * WORDS.length);
        if (!selectedWords.includes(WORDS[randIndex])) {
            selectedWords.push(WORDS[randIndex]);
        }
    }
    return selectedWords;
}

export { getRandomWords };
